plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.15-SNAPSHOT'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.infiproton'
version = '0.0.1-SNAPSHOT'
description = 'advanced-rag'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

repositories {
    mavenCentral()
    maven { url = 'https://repo.spring.io/snapshot' }
}

ext {
    set('springAiVersion', "1.1.7")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'
    compileOnly 'org.projectlombok:lombok'
    developmentOnly 'org.springframework.boot:spring-boot-devtools'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    implementation 'org.apache.pdfbox:pdfbox:2.0.30'

    implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    runtimeOnly 'org.postgresql:postgresql'

    implementation 'net.sourceforge.tess4j:tess4j:5.13.0'
    implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'

    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'

}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

tasks.named('test') {
    useJUnitPlatform()
}
