spring:
  application:
    name: advanced-rag

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
    vectorstore:
      pgvector:
        initialize-schema: false
        dimensions: 1536

  datasource:
    url: jdbc:postgresql://localhost:5432/support_db
    username: postgres
    password: postgres

  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env

  endpoint:
    health:
      show-details: always